version: '3'

services:
  maintenance:
    build:
      context: .
    # image: ghcr.io/acidtib/kamal-maintenance:latest
    ports:
      - "8080:80"
    environment:
      - HEALTHCHECK_PATH=/healthz
      - LOGS_ENABLED=true
    volumes:
      - ./web/maintenance.html:/usr/share/caddy/index.html
      - ./web/favicon.ico:/usr/share/caddy/favicon.ico
